version: 2
jobs:
  build:
    working_directory: ~/westegg
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Checking for inconsistent dependency versions
          command: node common/scripts/install-run-rush.js check
      - run:
          name: Installing...
          command: node common/scripts/install-run-rush.js install
      - run:
          name: Building...
          command: node common/scripts/install-run-rush.js rebuild --verbose
